### ISSUE TITLE
Yup, no extension created

### ISSUE THREAD

**Issue by hhirsch** [tzyganu/UMC1.9#100]
I don't have time to step through the code but everything works but the main point. So it is zero stars from me.

**Comment by tzyganu** [comment]
@hhirsch Thanks for reporting this...yup..thanks for nothing.  
In fact take you have:
 - 0 stars from me for your capability of following instructions. 
 - 0 stars from me for your capability of debugging
 - 0 stars from me for your issue reporting technique.
 - 0 stars from me for your interest and patience.

**Comment by hhirsch** [comment]
Np. Yw. Thanks for the fast reply. Used magerun instead. Does not do a lot but worked nonetheless.

**Comment by dfelton** [comment]
Wow, I've seen some bad bug reports before. But this one is beyond me. @hhirsch, you win the fail award for sure.

**Comment by hhirsch** [comment]
I agree. I was kind of in a hurry. I will try to reproduce the problem when I find the time. Since 168 people seem to get it to run without a problem.
