### ISSUE TITLE
After creating module it is not showing in magento backend

### ISSUE THREAD

**Issue by uzairkhatri** [tzyganu/UMC1.9#101]
I have creating a module with 4 fields . It is working fine on my local host , but when I moved my site to server It is not showing the menu in backend and frontend also.

I have cleared the cache , disable the compiler and did everything that I found over the internet but still the issue is not resolved .

I am attaching the screenshots kindly check this .

![1](https://cloud.githubusercontent.com/assets/4406453/10388330/6569e1ea-6e82-11e5-9de3-bc1c1d736933.png)
![2](https://cloud.githubusercontent.com/assets/4406453/10388329/6568fa28-6e82-11e5-911f-a19e667b7378.png)

Kindly help me out.

**Comment by dfelton** [comment]
On your live server,

* Are you logged in as an administrator role with all privileges? Or one which has been assigned access to this menu item?
* Hate to ask this but are you sure all the extension's files have been properly uploaded? Here are the critical ones at least pertaining to your menu
  * app/etc/modules/MODULE_NAME.xml
  * app/code/CODE_POOL/MODULE_NAMESPACE/MODULE_NAME/etc/config.xml
  * app/code/CODE_POOL/MODULE_NAMESPACE/MODULE_NAME/etc/adminhtml.xml

**Comment by tzyganu** [comment]
@uzairkhatri Can you send me the xml for the module configuration. You can find it in `var/modulecreator/package/[Namespace]_[Module].xml`.  
Please send it at ultimate(dot)module(dot)creator(at)gmail(dot)com if you don't want to post it here.

**Comment by uzairkhatri** [comment]
Hi 
I am sending you the xml file , kindly check and let me know what is the issue .I was to upload my site on live server and holding just because of the slider issue.
Thanks
RegardsUzair Khatri

Date: Fri, 9 Oct 2015 04:46:17 -0700

**Comment by tzyganu** [comment]
@uzairkhatri Your namespace and module name start with a lowercase letter.  
I assume your dev machine is on windows and your live machine is on linux.  
Make your namespace `Homepage` instead of `homepage` and your module name `Slider` instead of `slider`.

**Comment by uzairkhatri** [comment]
ok ,

I made changes in somefile and folders but it gave me error.
Can you tell me on which files and folder I have to make the changes , as there are many files .

**Comment by tzyganu** [comment]
All the folders and class names have to be renames to use a capital letter for namespace and module name. I think it's better to recreate the extension again if you didn't do many modifications after it was created.

**Comment by tzyganu** [comment]
I will close this for now since a solution was offered.
