### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by inluxc** [tzyganu/UMC1.9#107]
It would be nice to add events like, before save and after save in the admin.

**Comment by tzyganu** [comment]
@inluxc The models and controllers created with the UMC can still be observed as any other entities from the core using the general events `$model_save_before` or `controller_action_predispatch_$action`.  
Or are you talking about other events? 
in this case, can you give an example?

**Comment by tzyganu** [comment]
This is closed due to inactivity.
