### ISSUE TITLE
Entity Attributes "Group" and different urls for parent pages (listing pages)

### ISSUE THREAD

**Issue by nowayyy36** [tzyganu/UMC1.9#122]
Hey there,

First, thanks for your amazing job ! 
Then, two enhancements that would be nice :

1 -
Give the possibility to group attributes in tabs during the creation of the entity field (like the product admin page). For entities with a lot of attributes, admin page would be less messy ;-)

2 - 
Different urls for the entities listing page, in order to handle seo / language urls :
http://monsite.com/en/partners : list partners EN
http://monsite.com/fr/partenaires : list partners FR
http://monsite.com/es/socios : list partners ES

Note : first message on github, didnt find how to add the "enhancement" tag.

**Comment by tzyganu** [comment]
@nowayyy36 Thanks for the suggestions. 
Sorry for disappointing you but "1" is not going to happen. I thought about that that in the past, but it's to complicated to build and it does not justify the added business value.  

And "2" I think is already implemented. You can managed the list url key from the system->configuration section and you can change the scope to a store view level to change it for different languages.

I will close this issue for now, but if you say that "2" is not implemented I will reopen it and dig further.
