### ISSUE TITLE
Black background around image frame

### ISSUE THREAD

**Issue by dfelton** [tzyganu/UMC1.9#128]
Curious if you have encountered issues where your resized images have a pesky black background around them. Despite setting the background to array(255,255,255) I cannot seem to get rid of this black area around the frame....

``` php
    /**
     * Return the URL for the image SRC
     *
     * @param Mage_Catalog_Model_Category $object
     * @return string
     */
    public function getImageUrl($category)
    {
        /* @var $img FirstScribe_Client_Helper_Catalog_Category_Image */
        $img = Mage::helper('firstscribe_client/catalog_category_image');
        $img->init($category, 'featured_image');
        $img->keepFrame(true);
        $img->keepTransparency(true);
        $img->keepAspectRatio(true);
        $img->backgroundColor(array(255,255,255));
        $img->resize(250);

        return $img->__toString();
    }
```

Example Result:

![img](https://cloud.githubusercontent.com/assets/2659558/17531896/8ebc7a10-5e43-11e6-93c1-5420b287f91c.PNG)

The image helper itself is a class only very slightly modified from your typical UMC image helper, geared towards catalog/category entities. I've extended it just enough to support the necessary paths:

``` php
<?php
/**
 * catalog/category image helper
 *
 * @category    FirstScribe
 * @package     FirstScribe_Client
 * @author      Darren Felton <dfelton@firstscribe.com>
 */
class FirstScribe_Client_Helper_Catalog_Category_Image extends FirstScribe_Client_Helper_Catalog_Image_Abstract
{
    /**
     * image subdir
     * @var string
     */
    protected $_subdir = 'catalog/category';

}
```

```
<?php
/**
 * abstract catalog module image helper
 *
 * @category    FirstScribe
 * @package     FirstScribe_Client
 * @author      Darren Felton <dfelton@firstscribe.com>
 */
abstract class FirstScribe_Client_Helper_Catalog_Image_Abstract extends FirstScribe_Client_Helper_Image_Abstract
{
    /**
     * get the image base dir
     *
     * @access public
     * @return string
     */
    public function getImageBaseDir()
    {
        return Mage::getBaseDir('media').DS.$this->_subdir.DS;
    }

    /**
     * get the image url for object
     *
     * @access public
     * @return string
     */
    public function getImageBaseUrl()
    {
        return Mage::getBaseUrl('media').$this->_subdir.'/';
    }

    /**
     * get image url
     *
     * @access protected
     * @return mixed (string|bool)
     */
    protected function _getImageUrl()
    {
        if (!$this->_image) {
            return false;
        }
        if ($this->_scheduledResize) {
            return $this->getImageBaseUrl().$this->_resizeFolderName.'/'.$this->_getDestinationImagePrefix().'/'.$this->_image;
        } else {
           return $this->getImageBaseUrl().$this->_image;
        }
    }

}
```

Finally FirstScribe_Client_Helper_Image_Abstract is the typical [UMC abstract image helper](https://github.com/tzyganu/UMC1.9/blob/master/app/code/community/Ultimate/ModuleCreator/etc/source/app/code/Helper/Image/Abstract/010_content)

After an hour of banging my head to the wall I did find [this article](https://www.gravitywell.co.uk/latest/how-to/posts/fixing-black-magento-adds-to-image-backgrounds/) which is regarding this exact same topic but copying Varien_Image_Adapter_G2 to my local codePool and performing the modifications in the article yielded no results.

Any thoughts here? Have your image resizing with `$imgHelper->keepFrame(true)` parameter encountered this issue before?

**Comment by dfelton** [comment]
I've narrowed down the true source of the problem. Magento's very own [Varien_Image_Adapter_Abstract::backgroundColor()](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/lib/Varien/Image/Adapter/Abstract.php#L236) method is intended to be a getter/setter but the ```$this->_backgroundColor = $value``` statement is mistakenly not inside the method's main if statement. I don't know if this is a newly introduced bug of Magento or not... don't really care I guess, but I'll submit a report to them about it. 

Until Magento fixes their own code, it wasn't too hard to revise the UMC generated abstract image helper to accommodate for the bug in the Varien image processor. If I have time I'll try to update my branch of your extension and create a pull request. 

Just need to add this code to your [Abstract Image Helper](https://github.com/tzyganu/UMC1.9/blob/master/app/code/community/Ultimate/ModuleCreator/etc/source/app/code/Helper/Image/Abstract/010_content#L92)
```php
    /**
     * background color (r,g,b)
     * @var array
     */
    protected $_backgroundColor = array(255, 255, 255);
```


Then revise your [backgroundColor()](https://github.com/tzyganu/UMC1.9/blob/master/app/code/community/Ultimate/ModuleCreator/etc/source/app/code/Helper/Image/Abstract/010_content#L309) method to accomodate for Varien's inability to serve as a proper getter/setter. 

```php
    /**
     * Get/set keepBackgroundColor
     *
     * @access public
     * @param array $value
     * @return mixed(bool|{{Namespace}}_{{Module}}_Helper_Image_Abstract)
     */
    public function backgroundColor($value = null)
    {
        if ($value !== null) {
            $this->_backgroundColor = $value;
        }

        return $this->_getImageProcessor()->backgroundColor($this->_backgroundColor);
    }
```

**Comment by dfelton** [comment]
Just killing the subject a bit more... 

Looks like someone already reported the main issue [here](https://www.magentocommerce.com/bug-tracking/issue/index/id/1022).

Anyways, solution for UMC until Magento get's their sh*t together provided above :)  I'll create a pull request if you don't beat me to it.

**Comment by tzyganu** [comment]
@dfelton Feel free to open a PR. This project is kind of suspended for now from my point of view. I don't have time to add more things to it.

**Comment by dfelton** [comment]
@tzyganu 

Hello Marius.

Just want to extend one final thank you regarding your UMC 1.9. It came in handy again this year when I was working on a project. Also very much impressed my colleagues when I showed them your tool.

I'm going to close this issue mainly so that it can disappear from my own Issues page.

Cheers.
