### ISSUE TITLE
Access to Product/Category Collection in Entity List View?

### ISSUE THREAD

**Issue by paul-siteway** [tzyganu/UMC1.9#131]
How do I access the related products or category collection in the entity list template?

i tried: 
>$_entitiyname->getCategoryCollection();

**Comment by dfelton** [comment]
The generated class methods you are looking for is [$_entityName->getSelectedCategories()](https://github.com/tzyganu/UMC1.9/blob/master/app/code/community/Ultimate/ModuleCreator/etc/source/app/code/Model/Entity/150_category_relation#L24) and [$_entityName->getSelectedProducts()](https://github.com/tzyganu/UMC1.9/blob/master/app/code/community/Ultimate/ModuleCreator/etc/source/app/code/Model/Entity/140_product_relation#L24)

**Comment by dfelton** [comment]
Sorry if you're looking for the **collection object**, then use the methods in those same linked files, that end in "Collection".

- [$_entityName->getSelectedCategoriesCollection()](https://github.com/tzyganu/UMC1.9/blob/master/app/code/community/Ultimate/ModuleCreator/etc/source/app/code/Model/Entity/150_category_relation#L43)
- [$_entityName->getSelectedProductsCollection()](https://github.com/tzyganu/UMC1.9/blob/master/app/code/community/Ultimate/ModuleCreator/etc/source/app/code/Model/Entity/140_product_relation#L43)

**Comment by paul-siteway** [comment]
Thank you!
