### ISSUE TITLE
EAV / "Use Default Value" checkbox problem

### ISSUE THREAD

**Issue by aurmil** [tzyganu/UMC1.9#132]
hi

for an entity using EAV, when overwriting a parent value for the "status" field, the checkbox "Use Default Value" is always checked (but the value is correctly saved)

I guess it comes from [usedDefault()](https://github.com/tzyganu/UMC1.9/blob/7eb6c91d757474ee127c35e32ed44af56aae814f/app/code/community/Ultimate/ModuleCreator/etc/source/app/code/Block/Adminhtml/Module/Renderer/Fieldset/Element/010_content#L85)

it should be 

```php
return (false === $defaultValue);
```

instead of 

```php
return !$defaultValue;
```

as status = No is stored as a value = 0

regards

**Comment by tzyganu** [comment]
@aurmil thanks for this. I will take a look at it.

**Comment by alexandre-pereira** [comment]
Hello,

Any news about this issue?

I'll try to find where it comes next week, as this is not fixing the issue on my side.

**Comment by tzyganu** [comment]
@alexandre-pereira Totally forgot about this. It should be fixed now.
