### ISSUE TITLE
API: store scope, pictures...

### ISSUE THREAD

**Issue by lapause** [tzyganu/UMC1.9#33]
Hi,

I can't find out how to use the API generated for EAV entities. It works fine for simple entities, but it seems to me that :
- Pictures/files linked to entity must be handled manually, as according to wsdl the picture/file attributes are expecting a string. This can be achieved without too much work in local context, but this kind of defeat the all point of the API.
- There is no way to handle values for specific store context. the generated api.xml mentions a "currentStore" endpoint, but none is actually implemented. I've tried to add it manually from what exists in Mage/Catalog/Model/Api/Resource, but with no success so far.
In case of a multilingual store, this leaves half the content to enter by hand  :-/

Have I missed something?

**Comment by tzyganu** [comment]
I will close this due to inactivity and because I have no idea how to implement it.
