### ISSUE TITLE
Customer relationship

### ISSUE THREAD

**Issue by nadirs** [tzyganu/UMC1.9#34]
It would be useful to be able to link entities to customers the way you can already do with products.

**Comment by trodebac28** [comment]
I'm using this module output in a slighty different way, but I believe it can be useful to others. After adapting the output code, users on our website are creating entities on the front-end (only registered customers can do so) and we need to link these entities with the corresponding user that created them. "Linking entities to customes" would be a very useful feature. Also "Creating entities from the front end".

In any case, thanks for this great contribution.
Kind regards.

**Comment by alphahughes1** [comment]
I am brianhughes fuck that joker with a cat sleeping on his chest. Ginger snap. Ur quite active how many people on here are like me and had github switch frequency with my reality.
