### ISSUE TITLE
Problem with saving form / field values

### ISSUE THREAD

**Issue by ArchieWalker** [tzyganu/UMC1.9#50]
First of all, thank you for the great extension! 

I noticed that when I create an extension... It works just fine, but when I edit it and add other attribute fields these new fields dont work. 

Basically I do these steps:
1) I create extension, prepare all fields, click on Save.
2) Download extension and install it on website. Everything works fine.
3) Go back in Module Creator, add some new fields in extension.
4) Uninstal the extension from both folders and Database
5) Instal a new version of extension with new fields. 

On the website, in extension, I do see these new fields in both backend, and in Database as well... but when I click on save, the values are not saved, and I just get empty fields. in DB the values are NULL. 

I tried different field types, Image, WYSIWYG, Text etc... 

Always the same issue, after I add new fields on already created extension - the values dont get saved. 

I use UMC 1.9.4.1 with Magento CE 1.9.0.1

Regards,
Archie

**Comment by ArchieWalker** [comment]
Sorry for the late response. You were write, somehow it was cached even though I had cache disabled. 

Anyways, if someone else will have the same issue, just clear the cache as tzyganyu recommended, it should work just fine.

Again, thanks for the GREAT GREAT extension :))

**Comment by dfelton** [comment]
@ArchieWalker Just some additional information here, this is native behavior of Magento, not Marius' extension. 

If you were to say, write your own installer script to add a column to the `cms_page` table for example, the cache would have to be flushed before seeing this new column reflected in your `cms/page` model objects. Even if all cache types listed under System -> Cache Management have been turned off at the time that the installer script executed.

While I haven't reviewed what is all continued to be cached, one can see by looking at the var/cache directory that there are yet many items cached still when we have all the "registered" cache types, so to speak, turned off.
