### ISSUE TITLE
Just want to add a text field option per category

### ISSUE THREAD

**Issue by turbodonkey** [tzyganu/UMC1.9#77]
Not 100% sure how to do this, my use case may be too simple for this module. But basically I just want to add a simple text field variable to the category. Specifically to enable easy importing to 3rd party shopping sites, I need to map my store categories to the 3rd party category. Instead of doing this on a per product basis I simply wish to do this on a per category basis, then when i feed the products via XML to the 3rd party shopping site, I simply pull this custom text attribute of the category the product belongs to.

In all the experiments I have done, I can only produce a multi-drop down selector where it would list my pre-defined attributes. But I want this to simply be a free form text field?

**Comment by tzyganu** [comment]
@turbodonkey This is not in the scope of this extension.  
[See this](http://www.atwix.com/magento/add-category-attribute/), maybe it's what you need

**Comment by turbodonkey** [comment]
yeah thats exactly what I am using actually, just need the SOAP v2 hookins
tho, and thats driving me insane!!!
