### ISSUE TITLE
Entity Relationships Description

### ISSUE THREAD

**Issue by pljspahn** [tzyganu/UMC1.9#78]
In the help description for entity relationships, the description for "is child of" is ambiguous.

"The first entity acts as a child for the second one 
. A field will be added to the first entity table as a reference to the first entity."

Not sure how many times I have had to uninstall, fix, and reinstall a created module because I got this setting wrong (wanted "parent of" when I actually chose "child of" or vice versa).

**Comment by tzyganu** [comment]
@pljspahn Thank you for spotting this and sorry for the inconvenience. I fixed it.

**Comment by pljspahn** [comment]
In this case, the inconvenience was mostly due to my own laziness. Cheers Marius.
