### ISSUE TITLE
Not Enterprise compatible

### ISSUE THREAD

**Issue by Schrank** [tzyganu/UMC1.9#79]
Nothing I need, but FYI EE 1.12.0.2

The layout is f*cked up :-)

![bildschirmfoto 2015-02-05 um 15 42 08](https://cloud.githubusercontent.com/assets/379680/6062143/97fc4fcc-ad4d-11e4-857a-98334c4a45ba.png)

**Comment by tzyganu** [comment]
@Schrank By any chance are you using modman? If so, remember to set 'Allow symlinks' to "Yes": https://github.com/colinmollenhour/modman#requirements

And just for the record, the extension is not supposed to be compatible with EE (although it might work). I offer support for CE only (but for you I offer it for EE and even PE if you have one available :smile: ).

Let me know if the allow symlinks solves it.

**Comment by Schrank** [comment]
Let's not talk about this anymore :joy:
