### ISSUE TITLE
_uploadAndGetName

### ISSUE THREAD

**Issue by Schrank** [tzyganu/UMC1.9#81]
FYI the method _uploadAndGetName only supports file uploads without nested arrays. So in my example is the $input "1[image]" which works with Varien_Upload_File, but not with the generated

                if (isset($data[$input]['value'])) {
                    return $data[$input]['value'];
                }

Will comment when fixed :-)

**Comment by Schrank** [comment]
Fixed it with:

        } catch (Exception $e) {
            if ($e->getCode() != Varien_File_Uploader::TMP_NAME_EMPTY) {
                throw $e;
            } else {
                if ($this->getFileValue($data, $input)) {
                    return $this->getFileValue($data, $input);
                }
            }
        }
        return '';
    }

    private function getFileValue($data, $input)
    {
        $parts = explode('[', $input);
        $parts[] = 'value';
        while ($parts) {
            $data = $data[array_shift($parts)];
        }
        return $data;
    }

**Comment by tzyganu** [comment]
@Schrank Can you give me a scenario on how to replicate file uploads with nested arrays using the UMC?

**Comment by Schrank** [comment]
Having a tab, set form to have a suffix

        $form->setFieldNameSuffix('images');

and add an image field

    $fieldset->addField(
                'image' . $i,
                'image',
                array(
                    'label' => Mage::helper('landingpage')->__('Image'),
                    'name' => $language . $i . '[image]',
                )
            );

**Comment by tzyganu** [comment]
@Schrank I assume you added this manually. There is no way to generate this from the UMC.  
The UMC does not do everything, so if you change some aspect of the generated files you should handle the other aspects that are impacted by the changes.  
The `_uploadAndGetName` was intended to work with only one upload input at a time. Sorry but I will not implement this in the UMC.
