### ISSUE TITLE
Unable To Save Module in 1.9.1

### ISSUE THREAD

**Issue by teknology** [tzyganu/UMC1.9#84]
I receive this error when trying to save a module.
string(134) "/chroot/home/randsand/randsandbox.com/html/app/code/community/Ultimate/ModuleCreator/controllers/Adminhtml/ModulecreatorController.php" string(56) "Ultimate_ModuleCreator_Adminhtml_ModulecreatorController" {"error":false}

**Comment by teknology** [comment]
Seems the extension files need to be manually installed.

**Comment by tzyganu** [comment]
@teknology  Check if there is an echo somewhere in the code or a var_dump. I don't remember leaving this in the code. If you are still experiencig problems just send me by e-mail at `ultimate(dot)module(dot)creator(at)gmail(dot)com` the generated file for your extension located in `var/modulcreator/package/{Namespace}_{Module}.xml`
