### ISSUE TITLE
Module does not update after save

### ISSUE THREAD

**Issue by teknology** [tzyganu/UMC1.9#85]
It seems the extension does not update the module if settings have been changed.

**Comment by tzyganu** [comment]
@teknology I don't really understand you problem. Can you explain the steps you are taking?

**Comment by teknology** [comment]
I think i see the problem. I was using the option "Install extension" instead of "archive and install later". The extension doesn't over write files when updates are made which i can see makes sense. But i would like to be able to add custom files to the list of files this extension compresses. Mind pointing me in the right direction?

**Comment by tzyganu** [comment]
@teknology I don't understand your last request

>  But i would like to be able to add custom files to the list of files this extension compresses.

Give me an example please.

**Comment by micheledalonzo** [comment]
Hi, it's a really useful extension, saves hours of work; 
I've had same problem here: choosing "Install on current instance", first time all is ok; next time, after updating something (I've added an entity to manage) seems do not overwrite files in /app and other directory; package is build correct, so manual install is a solution; No error in sysloh; magento 1.9.2.4.

**Comment by tzyganu** [comment]
@micheledalonzo This is not a bug, it's a feature.  
I don't want the extensions overwriting ANY files in the current install.  
So if you choose to install the extension directly and one of the files already exists it will change that setting to "create archive". It's kind of a a fail-safe mechanism.
