### ISSUE TITLE
Image Helper

### ISSUE THREAD

**Issue by brandonjjon** [tzyganu/UMC1.9#89]
Hello,

I have a 'Image' type field, and on the frontend, it won't load the image (missing image icon). If I inspect the element, it's a 'data:image' type of link.

This is the code that is pulling the image:
`<img src="<?php echo Mage::helper('wabw_monthlyspecials/monthlyspecialtwo_image')->init($_monthlyspecialtwo, 'special_image')->resize(75);?>" alt="<?php echo $this->escapeHtml($_monthlyspecialtwo->getSpecialName());?>" />`

Resulting HTML: `<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEU......." alt="Spring Special">`
(didn't paste the full data:image url as it is very long)

Can anyone tell me why this isn't working?

**Comment by tzyganu** [comment]
@brandonjjon You are getting the `data:image` "thingy" when there is an error in resizing the image. 
You can start debugging in `[Namespace]_[Module]_Helper_Image_Abstract::__toString()`.  
The `data:image` is shown on the `catch` section. This means there is an exception in the resize. Also there is this line `Mage::logException($e);`. this means you should see the error in your `var/log/exception.log` file.  
I didn't experience this before. If I have to take a guess I would say there is something wrong with folder permissions. Make sure the `media` folder is writable. But I can's say for sure this is the issue.

**Comment by tzyganu** [comment]
I'm closing this issue as I cannot reproduce it and there was no response from the OP in more than 3 weeks.
