### ISSUE TITLE
Only first module

### ISSUE THREAD

**Issue by bartoss77** [tzyganu/UMC1.9#90]
Hi,
i have instelled UMC and created one module and place it in Catlog tab ant top but after i creating any other model with option install for current instance not working. Module not appaer in menu (when i try to install form downloaded zip same - not working). What can i do? editing module not working too... new attributes not appear in adminhtml (but are saved in module edit view).

Best regards

**Comment by tzyganu** [comment]
@bartoss77 I don't really understand your problem.  
You tried to create 2 modules and one is working and one not? 
Anyway...you should clear the cache and disable the compilation before installing a created module. 
In the folder `var/modulecreator/package` you will find an xml file for each extension your create in this format `Namespace_Module.xml` . PLease send me those files at the e-mail listed [in here](https://github.com/tzyganu/UMC1.9/wiki/issues).  
Also mention the magento version and the UMC version you are using. 
And explain in a few words the steps you follow that get you to your undesired result. 
This way I will be able to reproduce your issues on my side (if there is an issue) or maybe find what you are doing wrong.
