### ISSUE TITLE
Magento Best Practice

### ISSUE THREAD

**Issue by dfelton** [tzyganu/UMC1.9#98]
Sorry I don't mean to be a pest with minor issues here. As soon as I am able to I'll spend some time learning how to perform pull requests so minor patches can be more streamlined.

[This file](https://github.com/tzyganu/UMC1.9/blob/master/app/code/community/Ultimate/ModuleCreator/etc/source/app/code/Block/Entity/List/010_top) should have lines 18 and 20 modified to only have one underscore in the method name. So that it is extending the constructor method Magento's core development team intends for us to override. 

**Current Code:**
```php
    public function __construct()
    {
        parent::__construct();
```

**Magento Best Practice:**
```php
    public function _construct()
    {
        parent::_construct();
```

**Comment by dfelton** [comment]
Pull request created, closing this issue as it is now redundant.

**Comment by tzyganu** [comment]
@dfelton Don't need to say sorry. You are not being a pest. I really appreciate (and need) all the help I can get. This extension already became more than I can handle among other things and any helping hand is welcomed. Keep them coming :)
